version: "3.9"
# Environment variables
# are defined in //.env
services:
  db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5455:5432
  pgadmin:
    image: dpage/pgadmin4:6.15
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Admin@1234
    ports:
      - 5050:80
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      # Postgres host must
      # match service name
      # of postgres container:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - JWT_SECRET
    ports:
      - "4000:4000" # (app)
      - "9990:9229" # (debug)
    volumes:
      - ./api/src:/app/src:ro
      - ./api/node_modules:/app/node_modules:rw
      - ./api/package.json:/app/package.json:rw
      - ./api/package-lock.json:/app/package-lock.json:rw
  web:
    build:
      context: ./web
      args:
        FRONTEND_API_HTTP_ENDPOINT: http://localhost:4000/graphql
        FRONTEND_API_WS_ENDPOINT: ws://localhost:4000/graphql
    ports:
      - "3000:3000" # (app)
      - "9991:9229" # (debug)
    volumes:
      - ./web/src:/app/src:ro
      - ./web/public:/app/public:ro
      - ./web/node_modules:/app/node_modules:rw
      - ./web/package.json:/app/package.json:rw
      - ./web/package-lock.json:/app/package-lock.json:rw
